// <auto-generated />
namespace vividly_app.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class FixGenreInMovie : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FixGenreInMovie));
        
        string IMigrationMetadata.Id
        {
            get { return "202108241801590_FixGenreInMovie"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
